#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=preprocess_co3d
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=out_files/mast3r_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

cd $HOME/DL2/mast3r
source activate mast3r
srun python3 dust3r/datasets_preprocess/preprocess_co3d.py --co3d_dir data/co3d_subset --output_dir data/co3d_subset_processed  --single_sequence_subse
