#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=mast3r_rlbench_val
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=10:00:00
#SBATCH --output=out_files/rlbenval_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate mast3r

srun python augment_rlbench_with_mast3r_copy.py --data_path /scratch-shared/scur2608/rlbench/data/val --tasks push_buttons

