#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=close_jartrain
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=10:00:00
#SBATCH --output=out_files/train_close_jar_20-30_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate mast3r

srun python augment_rlbench_with_mast3r_copy2.py --data_path /scratch-shared/scur2608/rlbench/data/train --tasks insert_onto_square_peg push_buttons --begin 20 --end 30
